### ISSUE TITLE
Crash when no solution is found

### ISSUE THREAD

**Issue by lmeulen** [lmeulen/lRaptor#3]
**Describe the bug**
When the algorithm cannot provide a solution, this is not shown (traveltime is shown as 1440 minutes) and the application crashes during the journey printing.

**To Reproduce**
1. GTFS of NL, operator NS
2. From: Arnhem Zuid, To: Assen, Rounds: 2

**Expected result**
A message that no route could be found.

**Logfile**
python lRaptor.py --i gtfs --s "Arnhem Zuid" --e "Assen" --d "08:30:00" --r 2 --c True
2021-02-22 22:45:32,127 - DEBUG - Parameters     : ['--i', 'gtfs', '--s', 'Arnhem Zuid', '--e', 'Assen', '--d', '08:30:00', '--r', '2', '--c', 'True']
2021-02-22 22:45:32,127 - DEBUG - Input directoy : gtfs
2021-02-22 22:45:32,127 - DEBUG - Start point    : Arnhem Zuid
2021-02-22 22:45:32,127 - DEBUG - End point      : Assen
2021-02-22 22:45:32,127 - DEBUG - Departure time : 08:30:00
2021-02-22 22:45:32,127 - DEBUG - Rounds         : 2
2021-02-22 22:45:32,127 - DEBUG - Cached GTFS    : True
2021-02-22 22:45:32,252 - INFO - Reading GTFS took 0.1248 seconds
2021-02-22 22:45:32,252 - DEBUG - Agencies  : 1
2021-02-22 22:45:32,252 - DEBUG - Routes    : 140
2021-02-22 22:45:32,260 - DEBUG - Stops     : 866
2021-02-22 22:45:32,260 - DEBUG - Trips     : 31996
2021-02-22 22:45:32,260 - DEBUG - Stoptimes : 305913
2021-02-22 22:45:32,723 - DEBUG - Departure ID : [28, 27]
2021-02-22 22:45:32,723 - DEBUG - Arrival ID   : [10, 149, 150, 151]
2021-02-22 22:45:32,723 - DEBUG - Time         : 30600
2021-02-22 22:45:32,736 - DEBUG - Starting from IDS :
2021-02-22 22:45:32,736 - INFO - Analyzing possibilities round 1
2021-02-22 22:45:32,736 - INFO -     Stops to evaluate count: 2
2021-02-22 22:45:32,852 - DEBUG -          Evaluations    : 316
2021-02-22 22:45:32,852 - INFO -     Travel stops  calculated in 0.1126 seconds
2021-02-22 22:45:32,852 - DEBUG -     57 stops added
2021-02-22 22:45:32,927 - INFO -     Transfers calculated in 0.0760 seconds
2021-02-22 22:45:32,927 - INFO -     66 stops added
2021-02-22 22:45:32,927 - INFO -     90 stops to evaluate in next round
2021-02-22 22:45:32,936 - INFO - Analyzing possibilities round 2
2021-02-22 22:45:32,936 - INFO -     Stops to evaluate count: 90
2021-02-22 22:45:34,919 - DEBUG -          Evaluations    : 4279
2021-02-22 22:45:34,919 - INFO -     Travel stops  calculated in 1.9837 seconds
2021-02-22 22:45:34,919 - DEBUG -     293 stops added
2021-02-22 22:45:35,289 - INFO -     Transfers calculated in 0.3672 seconds
2021-02-22 22:45:35,289 - INFO -     338 stops added
2021-02-22 22:45:35,289 - INFO -     422 stops to evaluate in next round
2021-02-22 22:45:35,302 - INFO - Destination code   : 10
2021-02-22 22:45:35,302 - INFO - Time to destination: 1440.0 minutes
2021-02-22 22:45:35,302 - DEBUG - lRaptor Algorithm executed in 2.5795912999999997 seconds
2021-02-22 22:45:35,302 - INFO - Journey:
Traceback (most recent call last):
  File "C:\Users\XXXXXXXX\.conda\envs\gtfs\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\XXXXXXXX\.conda\envs\gtfs\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\XXXXXXXX\.conda\envs\gtfs\lib\cProfile.py", line 196, in <module>
    main()
  File "C:\Users\XXXXXXXX\.conda\envs\gtfs\lib\cProfile.py", line 189, in main
    runctx(code, globs, None, options.outfile, options.sort)
  File "C:\Users\XXXXXXXX\.conda\envs\gtfs\lib\cProfile.py", line 19, in runctx
    return _pyprofile._Utils(Profile).runctx(statement, globals, locals,
  File "C:\Users\XXXXXXXX\.conda\envs\gtfs\lib\profile.py", line 62, in runctx
    prof.runctx(statement, globals, locals)
  File "C:\Users\XXXXXXXX\.conda\envs\gtfs\lib\cProfile.py", line 100, in runctx
    exec(cmd, globals, locals)
  File "lRaptor.py", line 546, in <module>
    print_journey(journey, args.departure)
  File "lRaptor.py", line 421, in print_journey
    frm = a.stop_name.values[0]
IndexError: index 0 is out of bounds for axis 0 with size 0

**Desktop (please complete the following information):**
 - Python 3.7
 - Application Version: 22 februari 2021 (96ef67b)

**Additional context**
Apparently the evaluation at the end of perform_lraptor is no longer functioning.

**Comment by lmeulen** [comment]
Fixed in release https://github.com/lmeulen/lRaptor/commit/71cfc4c0534b323dd733b57367e161026249fe07

When there is no journey possible, the result is 0, check was on ''. This check on an empty string was an artifact from previous versions where the id's were stored as strings instead of integers.
